# Skosify configuration file for transforming Realfagstermer
#
# ./skosify.py realfagstermer/realfagstermer.ttl -c skosify.ini -o realfagstermer/realfagstermer.skosify.ttl

# runtime options which correspond to command line parameters
[options]
namespace=http://data.ub.uio.no/humord
label=Humord
default_language=nb
set_modified=True
from_format=turtle
aggregates=False
break_cycles=True
cleanup_properties=False
cleanup_classes=False
cleanup_unreachable=False
debug=False
enrich_mappings=False
keep_related=False
log=skosify.log
mark_top_concepts=False

# In the future we might want to enable this!
narrower=False

transitive=False

# define custom RDF namespaces that can then be used in the mappings below (and will also be used in the output file)
# Note that common namespaces are already defined: rdf, rdfs, owl, skos, dc, dct
[namespaces]
# FinnONTO SKOS Extensions namespace
# skosext=http://purl.org/finnonto/schema/skosext#
# MADS
# mads=http://www.loc.gov/mads/rdf/v1#
# ISO 25964 SKOS extensions
# isothes=http://purl.org/iso25964/skos-thes#

# define what to do with types in the source vocabulary, i.e. how these map to SKOS constructs
# key: CURIE or localname (string)
# value: CURIE or empty (to delete the instances)
# the <key> instances will be replaced with <value> instances.
# key may start with * which matches any localname prefix
# Note: use period '.' instead of colon ':' as separator in key CURIEs
[types]

# define what to do with literal properties on Concepts
# key: CURIE or localname (string)
# value: CURIE or empty (to delete the property)
# the <key> properties will be replaced with <value> properties
# key may start with * which matches any prefix
# Note: use period '.' instead of colon ':' as separator in key CURIEs
[literals]

# define what to do with relation properties on Concepts
# key: CURIE or localname (string)
# value: CURIE or empty (to delete the property)
# the <key> properties will be replaced with <value> properties
# key may start with * which matches any prefix
# Note: use period '.' instead of colon ':' as separator in key CURIEs
[relations]
